### ISSUE TITLE
mods.settings - invalid load order file when using script merger

### ISSUE THREAD

**Issue by MrJudge77** [Systemcluster/The-Witcher-3-Mod-manager#1]
script merger throws an error when loading mods.settings due to the first letter of _enable_ and _priority_ are not capitalized.

**Comment by Systemcluster** [comment]
Thanks for your report! I fixed the proper capitalization of the keys in `mods.settings` in [version `0.7.1`](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases). 
The next time the file is saved (just opening and closing the application should be enough) all keys should be capitalized.
