### ISSUE TITLE
Key Override prompt is unclear.

### ISSUE THREAD

**Issue by curtwagner1984** [Systemcluster/The-Witcher-3-Mod-manager#10]
This is the key override prompt:

![key_override_prompt](https://user-images.githubusercontent.com/20076369/71779625-1cb3e780-2fc0-11ea-8437-5cc5d9dd34cb.PNG)

In this example, the mod that is currently installing has the binding:
`IK_NONE=(Action=CastSignHold,State=Duration,IdleTime=0.2)`

And the current 'input.settings' has the binding:
`IK_Q=(Action=CastSignHold,State=Duration,IdleTime=0.2)`

So the label 'current' in the prompt refers to the currently set key. And 'original' refers to the new key. This is confusing. Many people consider 'original' to be the first. The one before modifications. The one that was before. It would be better if 'original' was renamed to 'new'.

Also, "Do you wish to keep the current key" is somewhat confusing... Will it not be better if the question was: "Do you want to override the current key"? 

Furthermore, it would be better if the prompt also contained the category where the key binding is changing. Such as [Horse], [Combat] etc...

**Comment by Systemcluster** [comment]
The message was made more clear in version `0.8.0`.

**Comment by Systemcluster** [comment]
The key rebind handling has been completely rewritten.
