### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by poperigby** [Systemcluster/The-Witcher-3-Mod-manager#11]
Is there a license for this project?

**Comment by Systemcluster** [comment]
Hi! Unfortunately there isn't a traditional license - Since this is a continuation of stefan3372's work, I couldn't just add one either. The closest you'll get is the "Terms and Permissions" section on the Nexus Mods page.

**Comment by poperigby** [comment]
I see. Kind of weird the original didn't have a license. Is stefan3372 completely gone from the scene, or could you ask them if you can license this?

**Comment by stefan3372** [comment]
Hi guys, @Systemcluster Chris, feel free to add open source license to the project. This is meant to be open source, i just forgot to add it :/

**Comment by Systemcluster** [comment]
That's great @stefan3372, thanks for the reply! Would you be okay with the [BSD 2-Clause](https://choosealicense.com/licenses/bsd-2-clause/) license?

**Comment by stefan3372** [comment]
@Systemcluster Yes, 2-Clause BSD is just fine :) Thanks
