### ISSUE TITLE
Load order column width isn't remembered

### ISSUE THREAD

**Issue by poperigby** [Systemcluster/The-Witcher-3-Mod-manager#13]
![T_20200902_153418](https://user-images.githubusercontent.com/20866468/92043844-c60ad300-ed31-11ea-8d8a-e5104718805d.png)

This keeps getting reset back to default after I've changed the width.

**Comment by Systemcluster** [comment]
Ah, another thing that's only stored on proper exit 😄

**Comment by Systemcluster** [comment]
Since changing the section sizes there didn't make much sense, I changed it so the mod name always fills as much space as possible and instead the size of the whole splitter is remembered.

**Comment by poperigby** [comment]
Makes sense. Thanks!
