### ISSUE TITLE
Public Linux Support

### ISSUE THREAD

**Issue by ShalokShalom** [Systemcluster/The-Witcher-3-Mod-manager#15]
Gratulations for the Linux support - it is virtually impossible now to find it 🤗 - can we release a dedicated version of your mod manager with announced Linux support and also mention it in the Readme? 
I send you a PR for the second part. Thanks 🥳

**Comment by Systemcluster** [comment]
Thank you! I'm planning to release a new version over the next few days after I got a few more correctness fixes in and I'll make sure to mention linux support.
