### ISSUE TITLE
Negative priority

### ISSUE THREAD

**Issue by poperigby** [Systemcluster/The-Witcher-3-Mod-manager#17]
Not sure if this is how the priority system works, but it would be nice to be able to set negative priority. Then you can specify which mods you want to load last instead of having to set the priority of all your mods.

**Comment by Systemcluster** [comment]
The priority system works like this: 

By default, mods are loaded in alphanumerical order based on their directory name - `modA` is loaded before `modB`, and so on. Every file that a mod provides - like scripts or bundled textures - is ignored for mods that load after it. E.g. if both `modA` and `modB` provide `content/scripts/game/r4player.ws`, only that of `modA` is loaded.

With the priority numbers you can override this - e.g. if you give `modA` a priority of `20` but `modB` a priority of `10`, then `modB` wins the conflict. A lower priority number means it's loaded first, so it has a higher "actual" priority. 

The game recognizes priorities from `1` to `9999` (correction: it's `0` to `9999`), so no negative numbers. And mods with a priority number are still loaded before ones without, so there's unfortunately no way around giving all your mods priorities if you want to load one at the very last, apart from naming it `modZ`.
