### ISSUE TITLE
Add prompt for path of witcher 3 settings/configs

### ISSUE THREAD

**Issue by cj360** [Systemcluster/The-Witcher-3-Mod-manager#18]
On Archlinux I've installed witcher 3 with lutris from GOG so I don't have the steam path `~/.local/share/Steam/steamapps/compatdata/292030/pfx/drive_c/users/steamuser/My Documents`.

After changing line 41 of src/util/util.py to my real config dir: `/home/andrew/Games/the-witcher-3-wild-hunt/drive_c/users/andrew/My Documents/`.

The mod manager wouldn't open till I changed the above directory not sure if its meant to ask the user to double check the path or not.

**Comment by Systemcluster** [comment]
Good to know that there are more option than Proton! A prompt makes sense if the path can't be found in the default locations.

**Comment by Systemcluster** [comment]
I added the option to select a documents path if it's not found in the pre-set locations.

**Comment by cj360** [comment]
Thanks! Both for the recent changes and working on a mod tool for windows & Linux!

**Comment by Systemcluster** [comment]
No problem!
