### ISSUE TITLE
More error...

### ISSUE THREAD

**Issue by vanja-san** [Systemcluster/The-Witcher-3-Mod-manager#2]
**When changing language, after I click Yes:**
![2019-05-13-21-43-43](https://user-images.githubusercontent.com/7201687/57630750-63377a80-75c8-11e9-96bd-ad612b7706e1.png)
**An error pops up:**
![2019-05-13-21-38-53](https://user-images.githubusercontent.com/7201687/57630427-c674dd00-75c7-11e9-9347-181a806628de.png)

**Comment by Systemcluster** [comment]
Thanks for your report! This is fixed in [version `0.7.1`](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases).
