### ISSUE TITLE
No module named 'easyprocess'

### ISSUE THREAD

**Issue by cj360** [Systemcluster/The-Witcher-3-Mod-manager#20]
Since I'm on arch I've been installing the dependencies through pacman rather than pip and I have `python-easyprocess` installed but the mod manager doesn't seem to detect it for some reason.

```
Installing All NPC Scabbards
No module named 'easyprocess'
> Installed 0 mods or dlcs (1 errors)
```

**Comment by Systemcluster** [comment]
I would recommend just setting up the virtual environment with pipenv. It won't touch your global python installation and works fine on Arch as well.

`easyprocess` is a dependency of `pyunpack`, and isn't used by the mod manager directly, so I don't think I can do much there.

**Comment by cj360** [comment]
I just installed easyprocess via pipenv and now the mod installed fine. I thought the pipenv setup would have installed the dependencies but I guess easyprocess was skipped.

**Comment by Systemcluster** [comment]
That's interesting, I guess I'll specify easyprocess as a separate dependency just to make sure. Thanks for letting me know!

**Comment by Systemcluster** [comment]
It seems like pipenv doesn't add sub-dependencies of platform specific dependencies to the lockfile, I've added it manually to the Pipfile now. Thanks again for the report!
