### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by basxto** [Systemcluster/The-Witcher-3-Mod-manager#21]
It would be nice being able to define folders via command line arguments.
The arguments could be `-d`/`--documents` and `-e`/`--executable`

Then one could start it with scripts like: (instead of going throug the dialogs the first time)
```
USER="someuse"
LUTRIS="/home/${USER}/Games/the-witcher-3-wild-hunt-game-of-the-year-edition/drive_c/"
pipenv run python main.py -d "${LUTRIS}users/${USER}/Meine Dokumente/" -e "${LUTRIS}GOG Games/The Witcher 3 Wild Hunt GOTY/bin/x64/witcher3.exe"
```

This is somewhat related to https://github.com/Systemcluster/The-Witcher-3-Mod-manager/issues/18

**Comment by DontBlnkBadWolf** [comment]
Is there a way to do something similar to this? It is currently placing folders into my One Drive Documents folder instead of placing them in my User Documents folder.

**Comment by Systemcluster** [comment]
Thank you for the suggestion! I added the following command line arguments:

```
-u USERDOCUMENTS, --userdocuments USERDOCUMENTS
    override the documents path
-g GAME, --game GAME
    override the game path
-c CONFIG, --config CONFIG
    override the config path 
```

**Comment by Systemcluster** [comment]
@DontBlnkBadWolf I'm not familiar with OneDrive, but currently the documents path is located by getting the default documents path from the Windows API. If this returns a OneDrive location, I assume OneDrive changes some configuration to override this.

If you are referring to mod manager configuration files, you can avoid storing data in your user documents (or OneDrive documents in your case) by moving your `config.ini` and other files into the mod manager directory. That path is then preferred for all files.

The save and config directory for The Witcher 3 is configured in `config.ini`, if that path was detected wrong you can correct it there.

Both options can now be set via command line arguments as well if you prefer.
