### ISSUE TITLE
Custom run command

### ISSUE THREAD

**Issue by basxto** [Systemcluster/The-Witcher-3-Mod-manager#22]
It would be nice if the run button could be disabled and/or a custom run command could be define.

The command for steam on linux would be `steam steam://rungameid/602320`

Running it through lutris could be `lutris lutris:rungameid/2038` etc.

There could also be command line arguments for that: `--run no`, `-r<path>`/`--run <path>`

**Comment by Systemcluster** [comment]
Thank you for the suggestion. I added a `gamelaunchcommand` configuration option - I only tested it on Windows with `gamelaunchcommand=C:/path/to/steam.exe steam://rungameid/602320`, if it doesn't work as expected on other platforms please re-open this issue!
