### ISSUE TITLE
Linux failed installation: cannot find file or directory

### ISSUE THREAD

**Issue by alexionut-tincu** [Systemcluster/The-Witcher-3-Mod-manager#25]
I tried installing it on Linux, and the following error showed up:

_FileNotFoundError: [Errno 2] No such file or directory: '/home/****/.local/share/Steam/steamapps/compatdata/292030/pfx/drive_c/users/steamuser/My Documents/The Witcher 3_

(the **** is the username, which it got right)

I strongly believe the only issue is that the program cannot find the path, because it doesn't exist. The folder it's trying to find is probably

_/home/****/.steam/steam/steamapps/compatdata/292030/pfx/drive_c/users/steamuser/Documents/The Witcher 3_

I read through the source code, but I am a complete newbie to Python, and I don't know how to make it find the right path.
![Screenshot_20211015_095929](https://user-images.githubusercontent.com/77517543/137445583-029404b1-f584-4d80-825b-cb833a4d18db.png)

**Comment by LynxLo** [comment]
I wrote an answer to this in another bug report and I think you have the same issue, here you go:

I had a similar problem, perhaps this can help:
FileNotFoundError: [Errno 2] No such file or directory: '/home/<yourusername>/.local/share/Steam/steamapps/compatdata/292030/pfx/drive_c/users/steamuser/My Documents/The Witcher 3'

In my case, all games are installed on a separate physical disk and I couldn't figure out how to change that in the code so instead I created a symlink where TW3MM expected to find the installation. Like this:

cd /home/<yourusername>/.local/share/
ln -s /media/username/games/Steam Steam

Where /media/username/games/Steam should be replaced with your own path to your Steam.

It was accepted and for the first time after several attempts the TW3MM actually started. Next problem, Script merger error: file cannot be found. So I guess there are more places in the code that need some attention. Not sure where yet...

**Comment by Systemcluster** [comment]
You can configure the paths with arguments:

https://github.com/Systemcluster/The-Witcher-3-Mod-manager/blob/c42e2024df733646810a54dfea8c2e227a46ddb4/main.py#L39-L47

Or inside the config file:

https://github.com/Systemcluster/The-Witcher-3-Mod-manager/blob/c42e2024df733646810a54dfea8c2e227a46ddb4/src/configuration/config.py#L62-L67
