### ISSUE TITLE
Case sensitive 'dlc' directory on linux

### ISSUE THREAD

**Issue by RypoFalem** [Systemcluster/The-Witcher-3-Mod-manager#27]
Installing a mod that puts contents in the dlc folder creates a separate DLC folder on linux.

https://github.com/Systemcluster/The-Witcher-3-Mod-manager/blob/bd7f41a1ee63f5f5ca210ff03891760ea46ebae8/src/configuration/config.py#L231

Changing `DLC` to `dlc` should fix that I think.

**Comment by ralgar** [comment]
On my Steam GOTY installation, the folder is called `DLC` by default. If that's not common across all installations, then it would require some other method to find the correct directory name, Simply changing to `dlc` would break other installations.

**Comment by Systemcluster** [comment]
Fixed in `0.9.2`, thanks for the report!
