### ISSUE TITLE
Top buttons do not open files

### ISSUE THREAD

**Issue by MrJudge77** [Systemcluster/The-Witcher-3-Mod-manager#3]
![buttons](https://user-images.githubusercontent.com/43927826/58033607-5e8a3d80-7b57-11e9-960b-a57502c3c3b1.png)

The top buttons suppose to open the corresponding file, however the directory is open instead.

**Comment by Systemcluster** [comment]
Thank you, this is fixed in [version `0.7.3`](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases).
