### ISSUE TITLE
Unable to specify Documents Path (linux)

### ISSUE THREAD

**Issue by Nightawkdude** [Systemcluster/The-Witcher-3-Mod-manager#30]
I was unable to figure out how to specify my documents path. It is having issues finding it since the mod manager and TW3 have separate virtual environments. This could possibly fix this by merging directories, but I think it would be better to have a specify path option like it has for game executable. In the meantime where I can I specify the path within the code? Not very familiar with python so my apologies if I missed something obvious.

**Comment by LynxLo** [comment]
I had a similar problem, perhaps this can help:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/<yourusername>/.local/share/Steam/steamapps/compatdata/292030/pfx/drive_c/users/steamuser/My Documents/The Witcher 3'`

In my case, all games are installed on a separate physical disk and I couldn't figure out how to change that in the code so instead I created a symlink where TW3MM expected to find the installation. Like this:

```
cd /home/<yourusername>/.local/share/
ln -s /media/username/games/Games/Steam Steam

```
Where /media/username/games/Games/Steam should be replaced with your own path to your Steam.

It was accepted and for the first time after several attempts the TW3MM actually started. Next problem, Script merger error: file cannot be found. So I guess there are more places in the code that need some attention. Not sure where yet...

**Comment by Systemcluster** [comment]
You can configure the paths with arguments:

https://github.com/Systemcluster/The-Witcher-3-Mod-manager/blob/c42e2024df733646810a54dfea8c2e227a46ddb4/main.py#L39-L47

Or inside the config file:

https://github.com/Systemcluster/The-Witcher-3-Mod-manager/blob/c42e2024df733646810a54dfea8c2e227a46ddb4/src/configuration/config.py#L62-L67
