### ISSUE TITLE
Pipfile requires a specific and old version of PySide2

### ISSUE THREAD

**Issue by LynxLo** [Systemcluster/The-Witcher-3-Mod-manager#31]
Hi!
Big disclaimer, I don't know much about python so it's quite possible that I can have done something wrong that caused this error. If that's the case, it would be really valuable to me if someone could explain what I did wrong.

Installation failed with:
`[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for pyside2==5.14.2.3`

It seems Pipfile requires PySide2 = "==5.14.2.3" and when I installed I got PySide2 5.15.2.1.
By editing the Pipfile and changing to 
`PySide2 = "==5.15.2.1"` 
the error disappeared. Should this be altered to instead require above a certain PySide2 version?

**Comment by Systemcluster** [comment]
I've replaced the deprecated `cchardet` with `charset-normalizer` and upgraded `PySide2` to the latest version; Installing the dependencies with Python versions `<=3.10` should work now.
