### ISSUE TITLE
Use patool directly instead of pyunpack

### ISSUE THREAD

**Issue by Conquerix** [Systemcluster/The-Witcher-3-Mod-manager#39]
Hello,
I had to modify the `fetcher.py` file is `src/core` not to use pyunpack and use patool directly.
I use NixOS and the way pyunpack calls patool (as a separate program and not via the API) makes it fundamentally incompatible with NixOS.
I replaced lines 268-269 in `src/core/fetcher.py` with:
```python
import patoolib
patoolib.extract_archive(modPath, outdir=extractedDir)
```
And this way I could correctly extract the mods.
In hope that it will help anyone

**Comment by Conquerix** [comment]
Small edit to the modification:
```python
import shutil
    if modPath.lower().endswith(".7z") or modPath.lower().endswith(".rar"):
        import patoolib
        patoolib.extract_archive(modPath, outdir=extractedDir)
    else:
        shutil.unpack_archive(modPath, extractedDir)
```
The previous code didn't handle zip files well

**Comment by Systemcluster** [comment]
Changed in `0.9.2`, thanks!
