### ISSUE TITLE
missing priority numbers

### ISSUE THREAD

**Issue by MrJudge77** [Systemcluster/The-Witcher-3-Mod-manager#4]
![image](https://user-images.githubusercontent.com/43927826/58071543-a5b41500-7bcf-11e9-8132-f74a5a519a5f.png)
the priority numbers in the load order / priority section is missing.

**Comment by Systemcluster** [comment]
I think I accidentally broke this when I changed the application to store the values in uppercase, I'll take a look.

**Comment by Systemcluster** [comment]
This is fixed in [version `0.7.3`](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases).
