### ISSUE TITLE
(Action=Focus,Reprocess) cannot be overwritten.

### ISSUE THREAD

**Issue by MrCementKnight** [Systemcluster/The-Witcher-3-Mod-manager#41]
I want to override (Action=Focus,Reprocess) in input.settings when installing a mod, but the mod manager ignores ",Reprocess".
The input.settings has (Action=Focus) added and the original (Action=Focus,Reprocess) remains.

**Comment by Systemcluster** [comment]
Fixed in `0.9.2`, thanks for the report!
