### ISSUE TITLE
TW3MM creates uppercase "DLC" folder instead of using existing lowercase

### ISSUE THREAD

**Issue by Sharparam** [Systemcluster/The-Witcher-3-Mod-manager#43]
**Problem:**

Installing the mod [Progress on the Path](https://www.nexusmods.com/witcher3/mods/6568?tab=description) puts the `dlcProgressOnThePath` folder inside a newly created `DLC` folder in the game directory, instead of the (existing) lowercase `dlc` folder. This makes things not work, presumably because the game does not look at the uppercase folder at all.

Manually moving the folder into the lowercase `dlc` folder makes the mod work.

As far as I can tell, this doesn't seem to be an issue with the mod, because inside the mod ZIP, the `dlc` folder is properly lowercase. It seems TW3MM creates this uppercase `DLC` folder on its own for some reason.

(I imagine this issue does not present on Windows, because it's case insensitive so even if TW3MM tries to reference an uppercase `DLC` folder the file system will just direct it to the existing lowercase one.)

From a quick glance at the code, it might be as easy as just changing `DLC` to `dlc` here: https://github.com/Systemcluster/The-Witcher-3-Mod-manager/blob/6904d7933a5914d241cb5d5fd2ec454f96175b88/src/configuration/config.py#L253

**Comment by Sharparam** [comment]
Actually after checking with some others, some people have uppercase DLC folder names in their vanilla installs? So now I'm not sure what is going on.

**Comment by Systemcluster** [comment]
Fixed in `0.9.2`, thanks for the report!
