### ISSUE TITLE
Linux: can't install .rar files

### ISSUE THREAD

**Issue by t0mtee** [Systemcluster/The-Witcher-3-Mod-manager#46]
Trying to install a .rar mod gives the error "Unknown archive format". I'm running Debian. Converting rar to zip can take a while, especially with big mods, so ideally rar extraction would be built in.

**Comment by t0mtee** [comment]
I've not noticed any issues with changing line 277 in `/src/core/fetcher.py` to just:
`        except:`

**Comment by Systemcluster** [comment]
I assume this has been fixed in #50. Thanks for the report and apologies for the late response!
