### ISSUE TITLE
Huge parts of input.settings not being processed when reinstalling a mod

### ISSUE THREAD

**Issue by t0mtee** [Systemcluster/The-Witcher-3-Mod-manager#48]
When reinstalling a mod, huge parts of input.settings are ignored by this regex expression:
![image](https://github.com/user-attachments/assets/2fab0736-32cf-4aa6-86ab-08a0b3192f41)
Which causes the file to become corrupted when the section is rewritten with only the modded keys and the game to completely regenerate the file in launch, removing the modded keys entirely.
This means you have to add the keys manually for modded keys to work at all.
Here's my input.settings: https://pastebin.com/xmh31wAj
I am running W3MM on Linux, if that matters.
As a workaround, you can regenerate input.settings (delete the file), then add the modded keys manually, and then set input.settings to read-only to avoid W3MM messing with it later.

**Comment by hunkyburrito** [comment]
Seems like it just doesn't match empty contexts and the `Version=##` lines. Not too hard to make the regex match those too. The file gets 'corrupted' because it stops matching after the empty context meaning everything after is not detected by W3MM.

The regex that *should* fix this is:
`(\[.*\]\s*((IK_.+=\(Action=.+\)|Version=\d+)\s*)*\s*)+`

I'll go ahead and create a PR for this fix soon

**Comment by t0mtee** [comment]
Thanks a bunch for looking into this!!

**Comment by Systemcluster** [comment]
Thanks for this report as well!

> The regex that _should_ fix this is: `(\[.*\]\s*((IK_.+=\(Action=.+\)|Version=\d+)\s*)*\s*)+`
> I'll go ahead and create a PR for this fix soon

Much appreciated! I used another approach in https://github.com/Systemcluster/w3modmanager/blob/master/w3modmanager/domain/mod/fetcher.py#L335; Perhaps it can be ported over if that regex turns out not to work for all cases.

**Comment by t0mtee** [comment]
So I've reinstalled the mods completely - still doesn't work. Here's some possible reasons I've found:

1. The [Death] category isn't present in the modded input.settings, but it is on the regenerated.
2. Same with [EMPTY_CONTEXT]
3. Same with [LootPopup]
4. Same with [TutorialPopup]

What is common between these four are that they are all empty categories - they have no keys in them. Just adding those isn't enough to fix the problem.

5. The [InputSettings] category isn't present, which contains the line "Version=43" (43 for me, I'm on 1.32).

Reasons 1-4 don't actually need to be amended for the input.settings to work, however Reason 5 is essential. To summarise, W3MM is still taking out the [InputSettings] category, which is essential for the game to work.

I'll post this comment on the PR and on the issue.

**Comment by hunkyburrito** [comment]
Well shoot. I thought I had it working, but I must've forgot about file permissions on my input.settings or something.

I've managed to re-add version matching in the latest commit on my fork, and from my testing, it seems like the modded keybinds stick around now, as you said. Do you think I should try to re-add empty contexts? They'll require a bit more tinkering, and I'm not sure they have much use to be honest.

**Comment by t0mtee** [comment]
Honestly thanks so much for your work, I greatly appreciate it.

I don't really see much reason to bother with the empty contexts. They don't have any effect and are generated by the game on boot so adding empty contexts will just complicate things.

Again, thanks :) I'll give this new commit a go

**Comment by t0mtee** [comment]
Just tested and everything seems to be good :) Let's hope this is all that needs to be done. Again, thanks a bunch.

**Comment by t0mtee** [comment]
Damn, I spoke to soon haha. Those empty contexts do have a use. I'm not sure the lack of which context causes this, but when one of them isn't present you'll be able to move the camera in the pause menu, which is obviously not intended behaviour. Adding them all back fixes this.

O hunkyburrito, I call on you one last time

**Comment by hunkyburrito** [comment]
Dang. Alright I'll work on getting them back in.

**Comment by t0mtee** [comment]
Thanks a bunch man

**Comment by hunkyburrito** [comment]
~~Do you mind testing with newest commit?~~ Nvm

**Comment by t0mtee** [comment]
I'm getting

```
string index out of range
Note: Additions to input.settings could not be automatically installed.
```

**Comment by hunkyburrito** [comment]
Okay, finally got it working. Should be good with my latest commit, lmk if you have any issues

**Comment by t0mtee** [comment]
I think it's so close. There is one thing I can see potentially being an issue - [TutorialPopup] isn't present in the newly generated file. Maybe because it's right at the bottom of the file with nothing underneath it:
![image](https://github.com/user-attachments/assets/04ca4d78-f9fc-47a0-b772-1ddc266efa93)
While the other empty contexts do have lines underneath them:
![image](https://github.com/user-attachments/assets/1a8c0e60-d62c-4102-931e-e96d112832b8)
Whether this lack of TutorialPopup will be an issue or not, I cannot say.

**Comment by hunkyburrito** [comment]
Oh, well that's really weird then because I still have it on my end. Is the input.settings file you're using the same as last time?

Just FYI, my process has been delete input.settings, start and close game to regenerate, reinstall mods, start and close game to check.

Edit: Only thing I can think of is the different versions of the game terminating the file differently? The code checks for 1 or 2 whitespaces after a context (and after removing 1 whitespace from the end of the file) which seems to work for me on latest game version, but maybe there's less whitespace on older game versions?

I updated the last commit to not strip out the last whitespace which will probably fix it for you.

**Comment by t0mtee** [comment]
Ah yes, that's where the issue was - I hadn't regenerated the input.settings by launching the game (which adds the other line of whitespace, I think both versions have 2 lines at the end of the whole process), so that's why it wasn't being added.

With this new commit, I think everything is good :) Thank you so much
