### ISSUE TITLE
Spaces in mods.settings file

### ISSUE THREAD

**Issue by Gavvers** [Systemcluster/The-Witcher-3-Mod-manager#7]
Using v0.7.5, I was encountering an error when trying to run Script Merger:

> Your mods settings file is invalid.
> Unrecognized value on line 2:
> Enabled = 1

Looking at the source code, I noticed that in config.py write() method sets space_around_delimiters to true by default, which causes the above error. I do not have a python dev environment setup here, so I cannot test changing that parameter default, but it seems like a good candidate for the cause of this issue.

Strangely, though, I did not experience this error when I first installed TW3MM, but I looked at the config file and don't see what could have changed...

Apologies for not being able to test this myself. Please let me know if you need more info.

**Comment by Systemcluster** [comment]
Thank you for the report! I'll look into it.

**Comment by MrJudge77** [comment]
hmm.. this doesn't seem to affect me... what version of script merger are you using?

**Comment by Gavvers** [comment]
> 
> 
> hmm.. this doesn't seem to affect me... what version of script merger are you using?

Latest on NexusMods, v0.6.2.

**Comment by MrJudge77** [comment]
okay did you install the unofficial patch for script merger in nexus mods?

Try that as well. I'm using both and haven't had any problems.

![image](https://user-images.githubusercontent.com/43927826/65310560-2d7f4f80-dbc1-11e9-8dac-f912ee6cd0d5.png)

**Comment by Gavvers** [comment]
Thanks for the tip about the unofficial patch.

I applied it and the error is gone, thanks!

**Comment by Systemcluster** [comment]
Glad you got it working! Unfortunately I haven't had much time in the past few weeks, but at some point I should probably look into the issue in a bit more detail. Until then I'll add a note to the readme about this.

Thanks for the help @MrJudge77!

**Comment by Systemcluster** [comment]
I changed it to omit the spaces in [version 0.7.6](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases), so there should be no more issues with old Script Merger versions.
