### ISSUE TITLE
Dynamic Height and Width for Right section

### ISSUE THREAD

**Issue by JARVIS-AI** [Systemcluster/The-Witcher-3-Mod-manager#8]
Is this fork has sizable right section of main Window ?

The section that show us **Load Order** and **Priority** 
Cause I was going to implement this feature but I found your fork that plays little time in long way of original one and it's good fork, so if it's not implemented yet can you add this ?
And It's annoying that in original release the right section is **FIXED** and when we adjust Load Order column, horizontal scroll bar appear

I didn't test your releases yet, just wanna be sure

Thanks

**Comment by JARVIS-AI** [comment]
Also I noticed that you ignore .idea files / folder
Can you acknowledge that folder so we can proceed develop with same config ?

**Comment by Systemcluster** [comment]
At the moment the section size is still fixed, but it shouldn't be too much work to change that. Thank you for the suggestion!

>Also I noticed that you ignore .idea files / folder
>Can you acknowledge that folder so we can proceed develop with same config ?

I don't use the JetBrains products, and I don't think keeping various editor configurations in the repository is a good idea anyway. 
I'll include a `.editorconfig` instead, which should cover most editors (JetBrains has an [official plugin](https://plugins.jetbrains.com/plugin/7294-editorconfig) for it as well). For the python environment there is already the `Pipfile` for Pipenv (which PyCharm also [supports](https://www.jetbrains.com/help/pycharm/pipenv.html)).

**Comment by Systemcluster** [comment]
I added some relevant project configuration files and made the splitter resizable in [version 0.7.7](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases).
