### ISSUE TITLE
cx_Freeze: Python error in main script for v7.11

### ISSUE THREAD

**Issue by MrJudge77** [Systemcluster/The-Witcher-3-Mod-manager#9]
no issue with v7.10

![image](https://user-images.githubusercontent.com/43927826/67273868-e357f980-f4f1-11e9-84b4-4f6feffe2592.png)

**Comment by IanMoyes** [comment]
I'm also getting this error message on this build.

**Comment by Systemcluster** [comment]
And I was already wondering why upgrading the packaging tool made the build smaller :) It looks like after the upgrade it missed to include some files that are necessary on some system configurations. I'll upload a new build in a few hours.

**Comment by Systemcluster** [comment]
The new build should work again, could you check?

**Comment by Systemcluster** [comment]
The new build should work again, could you confirm?
